// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm7Ad4I26Lbm4qaYZP-qkFKHCmtLpVTfg',
    appId: '1:1067453864086:web:9a9b9b51e2962ebaf58ab7',
    messagingSenderId: '1067453864086',
    projectId: 'our-family-calendar',
    authDomain: 'our-family-calendar.firebaseapp.com',
    storageBucket: 'our-family-calendar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHxSGuy0Ytt8F8VEtDyDwYTIvk4yah9ns',
    appId: '1:1067453864086:android:d4e281c0215a3b51f58ab7',
    messagingSenderId: '1067453864086',
    projectId: 'our-family-calendar',
    storageBucket: 'our-family-calendar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS1QpUEXVIzumM3tTs9q0zzQJOiPfOMjU',
    appId: '1:1067453864086:ios:f32850602c43379bf58ab7',
    messagingSenderId: '1067453864086',
    projectId: 'our-family-calendar',
    storageBucket: 'our-family-calendar.appspot.com',
    iosBundleId: 'com.example.ourFamilyCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS1QpUEXVIzumM3tTs9q0zzQJOiPfOMjU',
    appId: '1:1067453864086:ios:bde85f47cfa00b6df58ab7',
    messagingSenderId: '1067453864086',
    projectId: 'our-family-calendar',
    storageBucket: 'our-family-calendar.appspot.com',
    iosBundleId: 'com.example.ourFamilyCalendar.RunnerTests',
  );
}
